import { expect, test } from '@playwright/test'

test.use({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Helsinki' })

test('selects a calendar date and types time, preserving Cancel and trigger focus', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-03T12:00:00+03:00') })
  await page.goto('/#past')
  const trigger = page.getByLabel('Started · date and time', { exact: true })
  await trigger.click()
  const picker = page.getByRole('dialog', { name: 'Started · date and time', exact: true })
  await expect(picker).toBeVisible()
  await expect(picker.getByRole('spinbutton')).toHaveCount(0)
  const chosenDay = picker.getByRole('button', { name: 'Thursday, October 1, 2026', exact: true })
  const time = picker.getByRole('textbox', { name: 'Time', exact: true })
  await chosenDay.click()
  await expect(chosenDay).toHaveAttribute('aria-pressed', 'true')
  await time.fill('0930')
  await picker.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveText('Choose date and time')
  await trigger.click()
  await chosenDay.click()
  await time.fill('25:00')
  await expect(picker.getByRole('button', { name: 'Done', exact: true })).toBeDisabled()
  await time.fill('09:30')
  await time.press('Enter')
  await expect(picker).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveText('Oct 1, 2026, 9:30 AM')
  await trigger.click()
  await expect(chosenDay).toHaveAttribute('aria-pressed', 'true')
  await expect(time).toHaveValue('09:30')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveText('Oct 1, 2026, 9:30 AM')
})

test('keeps the calendar and typed-time controls reachable on small screens', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#past')
  await page.addStyleTag({ content: ':root { font-size: 200%; }' })
  await page.getByLabel('Started · date and time', { exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Started · date and time', exact: true })
  const widths = await picker.evaluate((dialog) => ({ client: dialog.clientWidth, scroll: dialog.scrollWidth }))
  expect(widths.scroll).toBeLessThanOrEqual(widths.client)
  await picker.getByRole('textbox', { name: 'Time', exact: true }).scrollIntoViewIfNeeded()
  await expect(picker.getByRole('textbox', { name: 'Time', exact: true })).toBeInViewport({ ratio: 1 })
  await page.setViewportSize({ width: 390, height: 260 })
  await picker.getByRole('textbox', { name: 'Time', exact: true }).scrollIntoViewIfNeeded()
  await expect(picker.getByRole('textbox', { name: 'Time', exact: true })).toBeInViewport({ ratio: 1 })
  await picker.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(picker).toHaveCount(0)
})
