import { expect, test } from '@playwright/test'

test.use({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Helsinki' })

test('can start another headache immediately after ending one', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.getByRole('link', { name: 'Log a current headache', exact: true }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Earlier headaches' }).getByRole('link')).toHaveCount(1)
})

test('shows a fresh Today on next-day reopen and retains the previous record', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T12:00:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T12:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { level: 1, name: 'Headache diary' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log a current headache', exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Earlier headaches' }).getByRole('link').click()
  await expect(page.getByRole('heading', { name: 'Timeline', exact: true })).toBeVisible()
  await expect(page.getByText('Headache ended', { exact: true })).toBeVisible()
})

test('opens scroll wheels and only changes the time when confirmed', async ({ page }) => {
  await page.goto('/#past')
  await page.getByLabel('Started · date and time', { exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Started · date and time', exact: true })
  await expect(picker).toBeVisible()
  await expect(picker.getByRole('spinbutton')).toHaveCount(5)
  for (const wheel of await picker.getByRole('spinbutton').all()) {
    await expect(wheel.locator('.date-wheel-option--selected')).toBeInViewport({ ratio: 1 })
    const selected = await wheel.locator('.date-wheel-option--selected').boundingBox()
    const column = await wheel.boundingBox()
    expect(Math.abs(selected!.y + selected!.height / 2 - (column!.y + column!.height / 2))).toBeLessThan(1)
  }
  const minutes = picker.getByRole('spinbutton', { name: 'Minute', exact: true })
  await minutes.press('Home')
  await minutes.press('ArrowDown')
  await expect(minutes).toHaveAttribute('aria-valuenow', '1')
  await minutes.evaluate((wheel) => { wheel.scrollTop = 44 * 30 })
  await expect(minutes).toHaveAttribute('aria-valuenow', '30')
  await picker.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Started · date and time', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Started · date and time', { exact: true })).toHaveText('Choose date and time')
  await page.getByLabel('Started · date and time', { exact: true }).click()
  await picker.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByLabel('Started · date and time', { exact: true })).not.toHaveText('Choose date and time')
})

test('refreshes completed Today on resume and preserves ongoing headaches across days', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T12:00:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T12:00:00+03:00'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByRole('heading', { name: 'Ready for a new day.' })).toBeVisible()
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log a current headache' })).toHaveCount(0)
})

test('keeps the existing 24-hour Undo window across a day boundary', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T23:30:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T08:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Ready for a new day.' })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
})

test('keeps long forms and their footer reachable at a narrow, enlarged-text viewport', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#past')
  await page.addStyleTag({ content: ':root { font-size: 200%; }' })
  await page.getByRole('button', { name: 'Add a dose' }).click()
  const widths = await page.locator('.diary-main').evaluate((main) => ({ client: main.clientWidth, scroll: main.scrollWidth }))
  expect(widths.scroll).toBeLessThanOrEqual(widths.client)
  await page.getByLabel('Optional note').scrollIntoViewIfNeeded()
  await expect(page.getByLabel('Optional note')).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Save headache' })).toBeInViewport({ ratio: 1 })
  await page.setViewportSize({ width: 390, height: 260 })
  await expect(page.getByRole('button', { name: 'Save headache' })).toBeInViewport({ ratio: 1 })
})
