import { expect, test } from '@playwright/test'

test.use({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Helsinki' })

test('can start another headache immediately after ending one', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.getByRole('link', { name: 'Log a current headache', exact: true }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Earlier headaches' }).getByRole('link')).toHaveCount(1)
})

test('shows a fresh Today on next-day reopen and retains the previous record', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T12:00:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T12:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { level: 1, name: 'Headache diary' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log a current headache', exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Earlier headaches' }).getByRole('link').click()
  await expect(page.getByRole('heading', { name: 'Timeline', exact: true })).toBeVisible()
  await expect(page.getByText('Headache ended', { exact: true })).toBeVisible()
})

test('selects a calendar date and types time, preserving Cancel and trigger focus', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-03T12:00:00+03:00') })
  await page.goto('/#past')
  const trigger = page.getByLabel('Started · date and time', { exact: true })
  await trigger.click()
  const picker = page.getByRole('dialog', { name: 'Started · date and time', exact: true })
  await expect(picker).toBeVisible()
  await expect(picker.getByRole('spinbutton')).toHaveCount(0)
  const chosenDay = picker.getByRole('button', { name: 'Thursday, October 1, 2026', exact: true })
  const time = picker.getByRole('textbox', { name: 'Time', exact: true })
  await chosenDay.click()
  await expect(chosenDay).toHaveAttribute('aria-pressed', 'true')
  await time.fill('0930')
  await picker.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveText('Choose date and time')
  await trigger.click()
  await chosenDay.click()
  await time.fill('25:00')
  await expect(picker.getByRole('button', { name: 'Done', exact: true })).toBeDisabled()
  await time.fill('09:30')
  await time.press('Enter')
  await expect(picker).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveText('Oct 1, 2026, 9:30 AM')
  await trigger.click()
  await expect(chosenDay).toHaveAttribute('aria-pressed', 'true')
  await expect(time).toHaveValue('09:30')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveText('Oct 1, 2026, 9:30 AM')
})

test('keeps the calendar and typed-time controls reachable on small screens', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#past')
  await page.addStyleTag({ content: ':root { font-size: 200%; }' })
  await page.getByLabel('Started · date and time', { exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Started · date and time', exact: true })
  const widths = await picker.evaluate((dialog) => ({ client: dialog.clientWidth, scroll: dialog.scrollWidth }))
  expect(widths.scroll).toBeLessThanOrEqual(widths.client)
  await picker.getByRole('textbox', { name: 'Time', exact: true }).scrollIntoViewIfNeeded()
  await expect(picker.getByRole('textbox', { name: 'Time', exact: true })).toBeInViewport({ ratio: 1 })
  await page.setViewportSize({ width: 390, height: 260 })
  await picker.getByRole('textbox', { name: 'Time', exact: true }).scrollIntoViewIfNeeded()
  await expect(picker.getByRole('textbox', { name: 'Time', exact: true })).toBeInViewport({ ratio: 1 })
  await picker.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(picker).toHaveCount(0)
})

test('refreshes completed Today on resume and preserves ongoing headaches across days', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T12:00:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T12:00:00+03:00'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByRole('heading', { name: 'Ready for a new day.' })).toBeVisible()
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log a current headache' })).toHaveCount(0)
})

test('keeps the existing 24-hour Undo window across a day boundary', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T23:30:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T08:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Ready for a new day.' })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
})

test('keeps long forms and their footer reachable at a narrow, enlarged-text viewport', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#past')
  await page.addStyleTag({ content: ':root { font-size: 200%; }' })
  await page.getByRole('button', { name: 'Add a dose' }).click()
  const widths = await page.locator('.diary-main').evaluate((main) => ({ client: main.clientWidth, scroll: main.scrollWidth }))
  expect(widths.scroll).toBeLessThanOrEqual(widths.client)
  await page.getByLabel('Optional note').scrollIntoViewIfNeeded()
  await expect(page.getByLabel('Optional note')).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Save headache' })).toBeInViewport({ ratio: 1 })
  await page.setViewportSize({ width: 390, height: 260 })
  await expect(page.getByRole('button', { name: 'Save headache' })).toBeInViewport({ ratio: 1 })
})
