import { expect, test } from '@playwright/test'

test.use({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Helsinki' })

test('refreshes Today on next-day reopen, retains the record and preserves the 24-hour Undo window', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T23:30:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T08:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Ready for a new day.' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log a current headache', exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Earlier headaches' }).getByRole('link').click()
  await expect(page.getByRole('heading', { name: 'Timeline', exact: true })).toBeVisible()
  await expect(page.getByText('Headache ended', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Back to Today' }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
})

test('refreshes completed Today on resume and preserves ongoing headaches across days', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T12:00:00+03:00') })
  await page.goto('/')
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.getByRole('button', { name: 'End headache now' }).click()
  await expect(page.getByRole('heading', { name: 'Glad it’s over.' })).toBeVisible()
  await page.clock.setFixedTime(new Date('2026-10-03T12:00:00+03:00'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByRole('heading', { name: 'Ready for a new day.' })).toBeVisible()
  await page.getByRole('link', { name: 'Log a current headache' }).click()
  await page.getByRole('button', { name: 'Save headache' }).click()
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00+03:00'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Headache ongoing' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log a current headache' })).toHaveCount(0)
})
